language: python
python:
  - "3.6"

notifications:
  email: false

install:
    - pip install cython numpy networkx scipy scikit-learn pandas gensim joblib gensim psutil --upgrade
    - pip install .

script:
  - echo "1"

